#! /usr/bin/env bash
#*******************************************************************************
# Copyright (c) 2026 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html,
# or the MIT License which is available at https://opensource.org/licenses/MIT.
# SPDX-License-Identifier: EPL-2.0 OR MIT
#*******************************************************************************

# Some portions generated by Co-Pilot

# Regenerates Maven settings files for all instances

set -o errexit
set -o nounset
set -o pipefail

IFS=$'\n\t'
SCRIPT_FOLDER="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
INSTANCES_DIR="${SCRIPT_FOLDER}/../instances"

# Check if instances directory exists
if [ ! -d "${INSTANCES_DIR}" ]; then
  echo "ERROR: instances directory not found at '${INSTANCES_DIR}'"
  exit 1
fi

# Process all instances
for instance in "${INSTANCES_DIR}"/*; do
  # Skip if not a directory
  if [ ! -d "${instance}" ] ; then
    continue
  fi
  
  echo "Processing instance: $(basename "${instance}")"
  "${SCRIPT_FOLDER}/regen_maven_settings.sh" "${instance}"
done

echo "Done. Maven settings regenerated for all instances."
